/**
 * skilldex-registry's half of the shared conformance corpus.
 *
 * This registry and the skilldex CLI implement the same published rubric from separate
 * code. On 2026-07-09 (d15aa6c) they diverged silently: this repo copied skilldex's weight
 * VALUES and its branch shape into a count-down loop, which inverts what a skipped `else`
 * means. A skill with no `name` scored 84 here against skilldex's 73, and a skill with no
 * `description` 84 against 67, for nearly two months. Neither suite noticed, because the
 * assertions here were `expect(score).toBeLessThan(100)` — true at 84, and true at 99.
 *
 * manifest.json is generated by skilldex, the reference implementation, from its own
 * fixtures. It is vendored here as a single self-contained file: it carries the SKILL.md /
 * SKILLSET.md content and file lists these validators need, so there are no fixture
 * directories to keep in step across two repositories.
 *
 * To update: regenerate in skilldex (`npx tsx tests/conformance-corpus/generate.ts`) and
 * copy manifest.json here. Never hand-edit an expectedScore to make this pass — a
 * disagreement means one of the two implementations is wrong, and which one is the finding.
 *
 * Coherence is in scope as of manifest format 2. This registry implements skillset spec 1.1, so
 * it must reproduce skilldex's coherence tallies as well as its conformance scores — from a
 * separate implementation, which is the whole point of the exercise.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join } from "path";
import { validateSkill } from "../../src/validator/index.js";
import { validateSkillset } from "../../src/validator/skillset.js";
import { checkSkillsetCoherence } from "../../src/validator/skillset-coherence.js";

const manifest = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "conformance-corpus", "manifest.json"), "utf8")
) as {
  formatVersion: number;
  skills: Array<{ id: string; skillMd: string; files: string[]; expectedScore: number }>;
  skillsets: Array<{
    id: string;
    skillsetMd: string;
    files: string[];
    embeddedSkillNames: string[];
    remoteSkillRefs: Array<{ name: string; source_url: string }>;
    expectedScore: number;
    blobs: Record<string, string>;
    expectedCoherence: {
      membersChecked: number;
      membersCoherent: number;
      passCount: number;
      warnCount: number;
      errorCount: number;
      declaredConventions: number;
    } | null;
  }>;
};

describe("conformance corpus — registry side", () => {
  it("is the format version this test understands", () => {
    // A bump means the manifest shape changed in skilldex and this file needs updating,
    // rather than the corpus quietly validating fewer things than it appears to.
    expect(manifest.formatVersion).toBe(2);
  });

  it("actually contains cases", () => {
    // A truncated or empty vendored copy would otherwise make this suite vacuously green.
    expect(manifest.skills.length).toBeGreaterThan(10);
    expect(manifest.skillsets.length).toBeGreaterThan(3);
  });

  for (const c of manifest.skills) {
    it(`skill ${c.id} scores ${c.expectedScore}, matching skilldex`, () => {
      const result = validateSkill({ skillMd: c.skillMd, files: c.files });
      expect(result.score).toBe(c.expectedScore);
    });
  }

  for (const c of manifest.skillsets) {
    it(`skillset ${c.id} scores ${c.expectedScore}, matching skilldex`, () => {
      const result = validateSkillset({
        skillsetMd: c.skillsetMd,
        files: c.files,
        embeddedSkillNames: c.embeddedSkillNames,
        remoteSkillRefs: c.remoteSkillRefs,
      });
      expect(result.score).toBe(c.expectedScore);
    });

    it(`skillset ${c.id} coheres as skilldex says it does`, async () => {
      // The manifest's blobs stand in for what the GitHub adapter fetches in production; the
      // file list answers the existence questions. Same inputs skilldex had from disk.
      const coherence = await checkSkillsetCoherence(
        {
          listFiles: () => c.files,
          async readFile(rel: string) {
            return Object.prototype.hasOwnProperty.call(c.blobs, rel) ? c.blobs[rel] : null;
          },
        },
        c.embeddedSkillNames
      );

      expect({
        membersChecked: coherence.membersChecked,
        membersCoherent: coherence.membersCoherent,
        passCount: coherence.passCount,
        warnCount: coherence.warnCount,
        errorCount: coherence.errorCount,
        declaredConventions: coherence.declaredConventions.length,
      }).toEqual(c.expectedCoherence);
    });
  }

  it("is checked against skillsets that actually declare conventions", () => {
    // Reproducing "all zeros" proves nothing about agreement checking. If the corpus ever loses
    // its contradiction case, this suite would keep passing while the hardest logic in the port
    // went unverified.
    const withConventions = manifest.skillsets.filter(
      (c) => (c.expectedCoherence?.declaredConventions ?? 0) > 0
    );
    expect(withConventions.length).toBeGreaterThan(0);
    expect(withConventions.some((c) => (c.expectedCoherence?.errorCount ?? 0) > 0)).toBe(true);
  });
});
