/**
 * skilldex-registry's half of the shared conformance corpus.
 *
 * This registry and the skilldex CLI implement the same published rubric from separate
 * code. On 2026-07-09 (d15aa6c) they diverged silently: this repo copied skilldex's weight
 * VALUES and its branch shape into a count-down loop, which inverts what a skipped `else`
 * means. A skill with no `name` scored 84 here against skilldex's 73, and a skill with no
 * `description` 84 against 67, for nearly two months. Neither suite noticed, because the
 * assertions here were `expect(score).toBeLessThan(100)` — true at 84, and true at 99.
 *
 * manifest.json is generated by skilldex, the reference implementation, from its own
 * fixtures. It is vendored here as a single self-contained file: it carries the SKILL.md /
 * SKILLSET.md content and file lists these validators need, so there are no fixture
 * directories to keep in step across two repositories.
 *
 * To update: regenerate in skilldex (`npx tsx tests/conformance-corpus/generate.ts`) and
 * copy manifest.json here. Never hand-edit an expectedScore to make this pass — a
 * disagreement means one of the two implementations is wrong, and which one is the finding.
 *
 * Coherence is deliberately out of scope. Skillset spec 1.1 is the coherence revision and
 * this registry implements 1.0, so the corpus asserts conformance scores only.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join } from "path";
import { validateSkill } from "../../src/validator/index.js";
import { validateSkillset } from "../../src/validator/skillset.js";

const manifest = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "conformance-corpus", "manifest.json"), "utf8")
) as {
  formatVersion: number;
  skills: Array<{ id: string; skillMd: string; files: string[]; expectedScore: number }>;
  skillsets: Array<{
    id: string;
    skillsetMd: string;
    files: string[];
    embeddedSkillNames: string[];
    remoteSkillRefs: Array<{ name: string; source_url: string }>;
    expectedScore: number;
  }>;
};

describe("conformance corpus — registry side", () => {
  it("is the format version this test understands", () => {
    // A bump means the manifest shape changed in skilldex and this file needs updating,
    // rather than the corpus quietly validating fewer things than it appears to.
    expect(manifest.formatVersion).toBe(1);
  });

  it("actually contains cases", () => {
    // A truncated or empty vendored copy would otherwise make this suite vacuously green.
    expect(manifest.skills.length).toBeGreaterThan(10);
    expect(manifest.skillsets.length).toBeGreaterThan(3);
  });

  for (const c of manifest.skills) {
    it(`skill ${c.id} scores ${c.expectedScore}, matching skilldex`, () => {
      const result = validateSkill({ skillMd: c.skillMd, files: c.files });
      expect(result.score).toBe(c.expectedScore);
    });
  }

  for (const c of manifest.skillsets) {
    it(`skillset ${c.id} scores ${c.expectedScore}, matching skilldex`, () => {
      const result = validateSkillset({
        skillsetMd: c.skillsetMd,
        files: c.files,
        embeddedSkillNames: c.embeddedSkillNames,
        remoteSkillRefs: c.remoteSkillRefs,
      });
      expect(result.score).toBe(c.expectedScore);
    });
  }
});
